version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80" # Local access via http://localhost
    depends_on:
      - nextjs
      - socket

  nextjs:
    container_name: nextjs
    image: shakenbake89/secret-h-next:latest
    environment:
      NODE_ENV: production
    depends_on:
      - socket

  socket:
    container_name: socket
    image: shakenbake89/secret-h-socket:latest
    environment:
      NODE_ENV: production
      SOCKET_PORT: "3001"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7-alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data:
